// List of all applications
// This module was initially generated by mano/scripts/generate-apps-list

'use strict';

module.exports = [
	"apps/business-process-demo",
	"apps/business-process-other-one",
	"apps/business-process-submitted",
	"apps/meta-admin",
	"apps/official-front-desk",
	"apps/official-processing",
	"apps/official-revision",
	"apps/official-social-security",
	"apps/public",
	"apps/user",
	"apps/users-admin"
];
